### ISSUE TITLE
maximum recursion depth exceeded while getting the str of an object clustermap

### ISSUE THREAD

**Issue by sundaresanab** [MaayanLab/clustergrammer#34]
Hi Nick,

We get this error 'maximum recursion depth exceeded while getting the str of an object clustermap', when we try to generate heatmap for the attached text file.
[deepa1892018122623.txt](https://github.com/MaayanLab/clustergrammer/files/2395611/deepa1892018122623.txt)

Also i tried uploading in it http://amp.pharm.mssm.edu/clustergrammer/ site, then i get the following error:

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log

Thanks in advance.

**Comment by cstill1992** [comment]
Hi all,

I'm having a similar issue with the command "net.cluster()". Does anyone have any insights into this? My data set is 23252 rows by 13230 columns where rows are genes and columns are cells. 

Code:
`>>> net.cluster(views=[])
Traceback (most recent call last):
  File "/Users/cstill/anaconda3/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 2787, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  File "/Users/cstill/anaconda3/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 2787, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  File "/Users/cstill/anaconda3/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 2787, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  [Previous line repeated 993 more times]
  File "/Users/cstill/anaconda3/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 2754, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  File "/Users/cstill/anaconda3/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 2666, in _dendrogram_calculate_info
    leaf_label_func, i, labels)
  File "/Users/cstill/anaconda3/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 2539, in _append_singleton_leaf_node
    ivl.append(str(int(i)))

RecursionError: maximum recursion depth exceeded while getting the str of an object`

Thanks,
Chris

**Comment by JoshuaFortriede** [comment]
I had the same problem with a large dataset. You can increase the number of recursions that python is allowed to use. 

import sys
sys.setrecursionlimit(100000)

**Comment by cornhundred** [comment]
I'm closing the issue due to apparent solutions. Feel free to reopen if necessary

**Comment by paulahsan** [comment]
> I had the same problem with a large dataset. You can increase the number of recursions that python is allowed to use.
> 
> import sys
> sys.setrecursionlimit(100000)

This one solved my problem
